global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'nginx'
    static_configs:
      - targets: ['sample_app:80']

rule_files:
  - "alert.rules"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

